-- MySQL Script generated by MySQL Workbench
-- Sat May  6 18:31:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema marketplace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marketplace` DEFAULT CHARACTER SET utf8 ;
USE `marketplace` ;

-- -----------------------------------------------------
-- Table `marketplace`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`users` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `name` VARCHAR(45) NULL,
  `lastName` VARCHAR(45) NULL,
  `password` VARCHAR(45) NOT NULL,
  `avatar` VARCHAR(45) NULL DEFAULT 'default-avatar.png',
  `createdAt` DATETIME NULL DEFAULT NOW(),
  `verificationCode` VARCHAR(64) NULL,
  `role` ENUM('root', 'admin', 'user') NULL DEFAULT 'user',
  `verifiedAt` DATETIME NULL,
  `bio` VARCHAR(255) NULL,
  `region` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `type` ENUM('store', 'regular') NULL,
  `taxNumber` VARCHAR(45) NULL,
  `Address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `marketplace`.`users` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `username_UNIQUE` ON `marketplace`.`users` (`username` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`products` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`products` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `keywords` VARCHAR(200) NULL,
  `idUser` INT UNSIGNED NOT NULL,
  `createdAt` DATETIME NULL DEFAULT now(),
  `updatedAt` DATETIME NULL,
  `isActive` TINYINT NULL DEFAULT 1,
  `locationName` VARCHAR(200) NULL,
  `locationLat` VARCHAR(45) NULL,
  `locationLong` VARCHAR(45) NULL,
  `status` ENUM('new', 'used', 'refurbished') NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idUser`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idVendor_idx` ON `marketplace`.`products` (`idUser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`productImages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`productImages` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`productImages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `fileName` VARCHAR(45) NOT NULL,
  `idProducts` INT UNSIGNED NOT NULL,
  `isDefault` TINYINT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id`)
    REFERENCES `marketplace`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`deals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`deals` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`deals` (
  `id` INT UNSIGNED NOT NULL,
  `idBuyer` INT UNSIGNED NOT NULL,
  `idProduct` INT UNSIGNED NOT NULL,
  `status` ENUM('requested', 'aproved', 'rejected', 'completed', 'cancelled') NOT NULL DEFAULT 'requested',
  `createdAt` DATETIME NULL DEFAULT now(),
  `completedAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idBuyer`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idProduct`)
    REFERENCES `marketplace`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `idBuyer_idx` ON `marketplace`.`deals` (`idBuyer` ASC) VISIBLE;

CREATE INDEX `idProduct_idx` ON `marketplace`.`deals` (`idProduct` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`follows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`follows` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`follows` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsers` INT UNSIGNED NOT NULL,
  `IdFollowed` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
     FOREIGN KEY (`idUsers`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
   FOREIGN KEY (`IdFollowed`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `followedId_idx` ON `marketplace`.`follows` (`IdFollowed` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`blacklists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`blacklists` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`blacklists` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsers` INT UNSIGNED NOT NULL,
  `idBlacklisted` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idUsers`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marketplace`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`reviews` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`reviews` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idDeals` INT UNSIGNED NOT NULL,
  `score` TINYINT NOT NULL,
  `comments` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idDeals`)
    REFERENCES `marketplace`.`deals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `score_UNIQUE` ON `marketplace`.`reviews` (`score` ASC) VISIBLE;

CREATE INDEX `idDeals_idx` ON `marketplace`.`reviews` (`idDeals` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`wishlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`wishlist` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`wishlist` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUsers` INT UNSIGNED NOT NULL,
  `idProducts` INT UNSIGNED NOT NULL,
  `status` TINYINT NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`idUsers`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`idProducts`)
    REFERENCES `marketplace`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `idUser_idx` ON `marketplace`.`wishlist` (`idUsers` ASC) VISIBLE;

CREATE INDEX `idProduct_idx` ON `marketplace`.`wishlist` (`idProducts` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `marketplace`.`complaints`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marketplace`.`complaints` ;

CREATE TABLE IF NOT EXISTS `marketplace`.`complaints` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUser` INT UNSIGNED NOT NULL,
  `idProduct` INT UNSIGNED NULL,
  `idDeals` INT UNSIGNED NULL,
  `idOtherUser` INT UNSIGNED NULL,
  `idReviews` INT UNSIGNED NULL,
  `message` VARCHAR(255) NULL,
  `status` ENUM('solved', 'pending', 'open', 'rejected') NOT NULL DEFAULT 'open',
  `ticketNumber` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
    FOREIGN KEY (`id`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id`)
    REFERENCES `marketplace`.`deals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id`)
    REFERENCES `marketplace`.`reviews` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    FOREIGN KEY (`id`)
    REFERENCES `marketplace`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
